### ISSUE TITLE
Folders support ?

### ISSUE THREAD

**Issue by jerefrer** [livinginthepast/fake_ftp#28]
Hi there,

Thanks for the great gem, I've been able to set it all up in a few minutes and I now can test ftp interaction. Awesome.

But in my case I would also like to check that the files are stored in the right remote folders.

What I'd like to do is something like:

``` ruby
# [...]

FtpManager.upload({
  filename: 'file.txt',
  remote_folder: 'folder',
  content: 'Test content'
})

expect(server.files).to include('folder/test.txt')
expect(server.file('folder/test.txt').data).to eq("Test content")
server.stop
```

Is it currently possible ?

**Comment by OndroNR** [comment]
+1

**Comment by sagax** [comment]
I think this question applies only to FTP protocol, principles of ftp

**Comment by MSchmidt** [comment]
+1

**Comment by joeljunstrom** [comment]
@livinginthepast would you accept a PR for this? My client is picky where I place files =)

**Comment by timraasveld** [comment]
I made a [branch](https://github.com/timraasveld/fake_ftp/tree/basic-directory-support) that adds basic folder support. It's a very basic string-based implementation and might break parts of the gem, which is why I didn't create a PR for it.

To add it to your project:
```ruby
gem 'fake_ftp', github: 'timraasveld/fake_ftp', branch: 'basic-directory-support'
```
Please note that it changes the implementation of `FakeFTP::Server#files and #file`. Where it would previously return `myfile.txt`, it now returns the full path: `/pub/myfile.txt`. `/pub` is the default path for FakeFTP, use the `FTP#chdir` command in your client to change it, like on a real FTP server.
